context_length: 8
batch_size: 4
overlap_frames: 2
skip_missing: true
optimizer:
  name: Adam
  optimizer_params:
    lr: 0.001
    betas: [0.9, 0.999]
    eps: 1e-8
    weight_decay: 0.0
    amsgrad: false
    foreach: null
    maximize: false
    capturable: false
    differentiable: false
    fused: null
loss_function:
  name: BCELoss
  loss_function_params:
    reduction: mean
n_epochs: 3
grad_clip: null
amp: false
checkpoint_path: model_checkpoints
validate_every_n_epochs: 1
checkpoint_monitor: f1_micro
checkpoint_mode: max
