context_length: 1000
batch_size: 4
overlap_frames: 10
skip_missing: true
optimizer:
  name: Adam
  optimizer_params:
    lr: 0.001
loss_function:
  name: BCELoss
  loss_function_params:
    reduction: mean
model:
  embed_dim: 64
  num_heads: 2
n_epochs: 5
grad_clip: null
amp: false
checkpoint_path: model_checkpoints
validate_every_n_epochs: 1
checkpoint_monitor: f1_micro
checkpoint_mode: max
